services:
    web:
        build:
            context: .
            dockerfile: DockerFile
        ports:
            - 8000:8000
        volumes:
            - .:/app
        command:
            sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

        depends_on:
            - db
        stdin_open: true
        tty: true
    db:
        image:
            postgres:latest
        ports:
            - 5432:5432
        volumes:
            - data:/var/lib/postgresql/data
        env_file:
            - ./env/.env.postgres
volumes:
    data:

