FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1


WORKDIR /app

COPY requirements.txt  /app/requirements.txt


RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install -r ./requirements.txt

COPY . .



