# Generated by Django 5.1.5 on 2025-03-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assetfileuploadhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfileuploadhistory',
            name='uploaded_file',
            field=models.FileField(upload_to='uploaded-files'),
        ),
        migrations.AlterField(
            model_name='assetfileuploadhistory',
            name='validated_file',
            field=models.FileField(null=True, upload_to='validated-files'),
        ),
    ]
